site_name: projset.io
nav:
  - Overview:
    - Architecture: index.md
    - Git Source Structure: git.md
    - Core Operator Resources: resources.md
    - ProjectSet App: app.md
  - Install: getting_started.md
  - User guide:
    - Basic UI: ui_guide.md
    - GPT ChatBot: gpt_guide.md
  - API: api.md

theme:
  name: material
  feature:
    tabs: true
    
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - render_swagger
  - search
